name: GitHub-Profile-3D-Contrib

on:
  schedule: # 04:00 UTC
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name AVMiraga
          git config user.email 93393424+AVMiraga@users.noreply.github.com
          git add -A .
          git commit -m "hi :D"
          git push
# github actions bot retired.
